library(magrittr)
library(data.table)
library(dplyr)
library(tidyr)
library(ggsci)
library(ggplot2)
library(ggrepel)
library(readr)
library(viridis)
library(ggnewscale)
library(reshape2)
library(stringr)
library(RColorBrewer)
library(cowplot)
library(patchwork)
library(scico)
library(colorspace)
library(ggpubr)
library(ggalluvial)
library(tidygraph)
library(igraph)
library(ggseqlogo)
library(ggVennDiagram)
#library(jsonlite)
#library(ggsankey)
#library(ggtern)
#library(ggExtra)
#library(corrplot)
#require(graphics)
library(dendextend)
library(circlize)
library(GGally)
#library(ggbump)
#library(ggradar)
#library(fmsb)
#library(lme4)
#library(merTools)
#library(bestNormalize)
#library(multilevelmod)
#library(gghighlight)
#library(ggcorrplot)
#library(corrr)
#library(FactoMineR)
#library(factoextra)
#library(UpSetR)
#library(ComplexHeatmap)

#library(ggfortify)
#library(circlize)

group_color <- scico(3, palette = 'davos')
names(group_color) <- c('CD', 'HC', 'UC')


my_colors <- c("Deep Purple" = "#673AB7",
               "Teal" = "#008080",
               "Coral" = "#FF6F61",
               "Berry" = "#D81B60",
               "Sapphire Blue" = "#0F52BA")

