library(magrittr)
library(data.table)
library(dplyr)
library(tidyr)
library(ggsci)
library(ggplot2)
library(ggrepel)
library(RColorBrewer)
library(jsonlite)
library(readr)
library(ggsankey)
library(ggtern)
library(viridis)
library(stringr)
library(cowplot)
library(ggExtra)
library(ggnewscale)
library(corrplot)
require(graphics)
library(reshape2)
library(dendextend)
library(GGally)
library(ggbump)
library(ggradar)
library(fmsb)
library(patchwork)
library(lme4)
library(merTools)
library(bestNormalize)
library(multilevelmod)
library(gghighlight)
library(ggcorrplot)
library(corrr)
library(FactoMineR)
library(factoextra)
library(UpSetR)
library(ComplexHeatmap)
library(circlize)
library(ggfortify)


my_colors <- c("Deep Purple" = "#673AB7",
               "Teal" = "#008080",
               "Coral" = "#FF6F61",
               "Berry" = "#D81B60",
               "Sapphire Blue" = "#0F52BA")